### ISSUE TITLE
prefab.web.portal.configure(production=False, ...)  doesn't set client_id and client_secret

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/lib9#120]
#### Installation information

- jumpscale version: 9.3.0
- operating system: Ubuntu 16.04

#### Detailed description

When passing `False` as the value for the `production` argument in
`prefab.web.portal.configure(production=False, client_id='ays-server-clients-org', client_secret=ays_clients_org_secret)` the values for `client_id` and `client_secret` are ignored.

This doesn't allow to setup an AYS Portal which is not configured to use ItsYou.online that needs to authenticate against an AYS Server that has ItsYou.online integrated.

Currently the values set for `client_id` and `secret` are both used by the portal when authenticating portal users (authorization code grant flow), and when the portal consumes the AYS server RESTful API, for which it gets a JWT (based on this client_id and password; client credentials flow) to authenticate against the AYS Server, even while the AYS Portal itself is set to be not in production.

#### Steps to reproduce

```python
import os
app_id = os.environ["APP_ID"]
secret = os.environ["SECRET"]
url = "se-gen-1.demo.greenitglobe.com"
client = j.clients.openvcloud.get(app_id, secret, url)
account = client.account_get("wimvdb", create=False) 
vdc = account.space_get("demo VDC", "se-gen-1")
path = os.path.expanduser("~/.ssh/mykey")
j.clients.ssh.load_ssh_key(path=path, create_keys=True)
ays_server_93 = vdc.machine_create("ays-server-93", "mykey", sizeId=3)
prefab = ays_server_93.prefab
internal_ip_address = ays_server_93.model["nics"][0]["ipAddress"]
public_ip_address = vdc.model["externalnetworkip"]
iyo_user = j.clients.itsyouonline.get_user(app_id, secret)
prefab.js9.js9core.install(branch='master')
prefab.js9.atyourservice.configure(production=True, organization='ays-server-clients-org')
cmd = "apt-get install python3-pip libffi-dev libpython3-dev libssh-dev libsnappy-dev build-essential python3-dev pkg-config libvirt-dev -y"
prefab.core.run(cmd)
prefab.js9.atyourservice.install(branch='master')
ays_server_93.portforward_create(5000, 5000)
prefab.js9.atyourservice.start(host="0.0.0.0")
ays_clients_org = iyo_user.organizations.get("ays-server-clients-org")
ays_clients_org_api_key = ays_clients_org.api_keys.get("ays-server-api-key")
ays_clients_org_secret = ays_clients_org_api_key.model["secret"]
prefab.js9.atyourservice.configure_api_console(url="http://{}:5000".format(public_ip_address))
prefab.web.portal.install(False)
ays_server_93.portforward_create(8200, 8200)
prefab.js9.atyourservice.load_ays_space()
internal_ays_url = "http://{}".format(internal_ip_address)
prefab.js9.atyourservice.configure_portal(internal_ays_url, 5000)
prefab.web.portal.configure(production=False, client_id='ays-server-clients-org', client_secret=ays_clients_org_secret)
prefab.web.portal.start()
```
As a result you'll get the following settings in the `[portal.main.oauth]` section of `~/js9host/cfg/jumpscale9.toml`, both `client_id` and `client_secret` have not been updated:
```toml
[portal.main.oauth]
token_url = "https://itsyou.online/v1/oauth/access_token"
client_logout_url = ""
organization = "testOrg"
client_secret = "..."
redirect_url = "http://ae5d255c.ngrok.io/restmachine/system/oauth/authorize"
client_scope = "user:email:main,user:memberof:JSPortal"
client_url = "https://itsyou.online/v1/oauth/authorize"
client_user_info_url = "https://itsyou.online/api/users/"
force_oauth_instance = ""
client_id = "JSPortal"
default_groups = ["admin", "user"]
```
