### ISSUE TITLE
SAL for capacity registration against etcd cluster

### ISSUE THREAD

**Issue by zaibon** [Jumpscale/lib9#238]
We need a SAL capable of registering node capacity onto an etcd cluster
The capacity of a node is measured in [resource units](https://docs.grid.tf/threefold/info/src/branch/master/concepts/resource_units.md), CRU, MRU, HRU,SRU

### types:
capacity in yaml format
```yaml
capacity:
  node_id: ..
  location: ..
  resource_units:
    CRU: ..
    MRU: ..
    HRU: ..
    SRU: ..
```
Later on we still need to include proof of capacity, but that will be for later iteration
### Methods
`register(node_id, capacity_obj)`: register capacity from a node
`list(location=None):` list all the capacity, optionally filter per location. return a list of capacity object
`get(node_id):` return the capacity for a single node
`search(location=None, mru=None, cru=None, hru=None,sru=None):` search based on location and minimum resource unit available, all argument are optional
Maybe we want to be able to remove some registered capacity, but that will be for later iteration
